#!/bin/bash
#############################################################
# Name:        Supportconfig Plugin for SUSE Cloud
# Description: Gathers important troubleshooting information
#              about SUSE Cloud
# License:     GPLv2
# Author:      Matt Barringer <mbarringer@suse.de>
# Modified:    2012 August 29
#############################################################

SVER=1.0.0
RCFILE="/usr/lib/supportconfig/resources/scplugin.rc"
LOG_LINES=5000  # 0 means include the entire file

[ -s $RCFILE ] && . $RCFILE || { echo "ERROR: Initializing resource file: $RCFILE"; exit 1; }

validate_rpm_if_installed() {
        thisrpm="$1"
        echo "#==[ Validating RPM ]=================================#"
        if rpm -q "$thisrpm" >/dev/null 2>&1; then
                echo "# rpm -V $thisrpm"

                if rpm -V "$thisrpm"; then
                        echo "Status: Passed"
                else
                        echo "Status: WARNING"
                fi
        else
                echo "package $thisrpm is not installed"
                echo "Status: Skipped"
        fi
        echo
}

pconf_files() {
        _log_files 0 "Configuration File" "$@"
}

plog_files() {
        loglines="$1"
        shift
        _log_files "$loglines" "Log File" "$@"
}

_log_files() {
        loglines="$1" title="$2"
        shift 2

        for file in "$@"; do
                _log_file "$loglines" "$title" "$file"
        done
}

_log_file() {
        loglines="$1" title="$2" file="$3"

        case "$file" in
                *.tbz|*.bz2|*.gz|*.zip)
                        continue
                        ;;
        esac

        if ! [ -f "$file" ]; then
                plugin_tag "$title" "$file - File not found"
                continue
        fi

        if [ "$loglines" -eq 0 ]; then
                plugin_tag "$title" "$file"
        else
                plugin_tag "$title" "$file - Last $loglines Lines"
        fi

        _capture "$loglines" "$file" | _capture_filter
        echo
}

_capture() {
        loglines="$1" file="$2"
        if [ "$loglines" -eq 0 ]; then
                cat "$file"
        else
                tail -"$loglines" "$file"
        fi
}

# test via: SUSECLOUD_PLUGIN_TEST=y ./susecloud
_filter_test_cases() {
        cat <<EOF
    "password": "s3kr1t",
    "token": "999888777666",
    "bmc_password": "s3kr1t",
    "machine-install": { "password": "s3kr1t" },
web_ui_admin_default_password "s3kr1t"
.... "bmc_user"=>"root", "bmc_password"=>"cr0wBar!"}, {"token"=>"l33t", ...
neutron_admin_password=s3kr1t
rabbit_password=s3kr1t
connection=postgresql://nova:s3kr1t@192.168.124.81/nova
   password: p4ssw0rt
   service_password: service_p4ssw0rt
   stack_domain_admin_password: 4dm1n_p4ssw0rt
   auth_encryption_key: 4u7h_ke7
EOF
}

CENSORED='<<CENSORED BY SUPPORTCONFIG PLUGIN>>'

_expected_test_results=$( cat <<EOF
    "password": "$CENSORED",
    "token": "$CENSORED",
    "bmc_password": "$CENSORED",
    "machine-install": { "password": "$CENSORED" },
web_ui_admin_default_password "$CENSORED"
.... "bmc_user"=>"root", "bmc_password"=>"$CENSORED"}, {"token"=>"$CENSORED", ...
neutron_admin_password=$CENSORED
rabbit_password=$CENSORED
connection=postgresql://nova:$CENSORED@192.168.124.81/nova
   password: $CENSORED
   service_password: $CENSORED
   stack_domain_admin_password: $CENSORED
   auth_encryption_key: $CENSORED
EOF
)

_capture_filter() {
        sed_args=(
                # "password": "s3kr1t",
                # "token": "999888777666",
                # "bmc_password": "s3kr1t",
                # "machine-install": { "password": "s3kr1t" },
                -e 's/\("\([a-z_]\+\)\?\(passw\(or\)\?d\|token\)":\? \+"\+\)[^"]\+"/\1'"$CENSORED"'"/gi'

                # web_ui_admin_default_password "s3kr1t"
                -e 's/^\( *\([a-z_]\+\)\?passw\(or\)\?d \+"\+\)[^"]\+"/\1'"$CENSORED"'"/i'

                # .... "bmc_user"=>"root", "bmc_password"=>"cr0wBar!"}, {"token"=>"l33t", ...
                -e 's/\("\([a-z_]\+\)\?\(passw\(or\)\?d\|token\)" *=> *"\+\)[^"]\+"/\1'"$CENSORED"'"/gi'

                # neutron_admin_password=s3kr1t
                # rabbit_password=s3kr1t
                -e 's/^\( *[a-z_]\+_password[a-z_]*=\).\+/\1'"$CENSORED"'/'

                # connection=postgresql://nova:s3kr1t@192.168.124.81/nova
                -e 's!^\( *\([a-z_]\+_\)\?connection[a-z_]*=[a-z]\+://[a-z_]\+:\)[^@]\+@!\1'"$CENSORED"'@!'
                # Filter passwords from crowbar batch export output
                # [   ] password: p4ssw0rt
                # [   ] service_password: service_p4ssw0rt
                # [   ] stack_domain_admin_password: 4dm1n_p4ssw0rt
                -e 's/\(^ *\(stack_domain_admin_\|service_\)\?password:\).*/\1 '"$CENSORED"'/'

                # [   ] auth_encryption_key: 4u7h_ke7
                -e 's/\(^ *auth_encryption_key:\).*/\1 '"$CENSORED"'/'
        )
        if (( ADD_OPTION_LOGS )); then
                sed_args+=( -e 's/^M//g' )
        else
                sed_args+=(
                        -e '/^[[:space:]]*#/d'
                        -e '/^[[:space:]]*;/d'
                        -e '/^[[:space:]]*\/\//d'
                        -e 's/^M//g'
                        -e '/^$/d'
                )
        fi
        sed "${sed_args[@]}"
}

if [ -n "$SUSECLOUD_PLUGIN_TEST" ]; then
        tmpdir=$( mktemp -d )
        _filter_test_cases | _capture_filter > $tmpdir/got
        echo "$_expected_test_results" > $tmpdir/expected
        if cmp $tmpdir/{got,expected}; then
                rm $tmpdir/{got,expected}
                rmdir $tmpdir
                exit 0
        else
                echo "Got unexpected test results:"
                diff -u $tmpdir/{got,expected}
                echo "Look in $tmpdir"
                exit 1
        fi
fi

#############################################################
section_header "Supportconfig Plugin for SUSE Cloud, v${SVER}"
# The plugin already hardcodes a reference to this directory above, so we're
# not introducing a new coupling with .spec files by using this absolute path here.
for thisrpm in $(cat "/usr/lib/supportconfig/resources/susecloud-rpm-list"); do
        validate_rpm_if_installed "$thisrpm"
done

find_and_pconf_files () {
        [ -d "$1" ] || return 0
        files=$(find "$@" ! -name \*.gz ! -name \*.bz2)
        if [ -n "$files" ]; then
                pconf_files $files
        fi
}

find_and_plog_files () {
        [ -d "$1" ] || return 0
        files=$(find "$@" ! -name \*.gz ! -name \*.bz2)
        if [ -n "$files" ]; then
                plog_files "$LOG_LINES" $files
        fi
}

#############################################################
section_header "Crowbar"

pconf_files \
        /etc/crowbar.install.key \
        /opt/dell/chef/data_bags/crowbar/bc-template-*.json
find_and_pconf_files /etc/crowbar                         -type f
find_and_plog_files  /opt/dell/crowbar_framework/log      -type f
find_and_pconf_files /var/lib/crowbar/config              -type f
find_and_plog_files  /var/log/nodes                       -type f
find_and_plog_files  /var/log -path /var/log/crowbar\*    -type f
find_and_plog_files  /var/log/apache2                     -type f
plugin_tag "admin node PXE / TFTP configuration"
find                 /srv/tftpboot/discovery/pxelinux.cfg -ls
echo; echo
find_and_pconf_files /srv/tftpboot/discovery/pxelinux.cfg -type f
find_and_pconf_files /srv/tftpboot/nodes                  -type f

#############################################################
section_header "Chef"

# Don't capture private keys/certificates, just show the inode info
[ -d /etc/chef ] && find /etc/chef -type f -name \*.pem -ls
echo; echo
find_and_pconf_files /etc/chef       -type f  ! -name \*.pem

find_and_plog_files  /var/log/chef   -type f
plog_files 0 \
        /var/chef/cache/chef-stacktrace.out \
        /var/chef/cache/failed-run-data.json

find_and_plog_files  /root           -name screenlog.\*

#############################################################
section_header "Ceph config"

if [ -d /etc/ceph ]; then
    if files=$(find /etc/ceph -type f | egrep -v '(/monmap|\.keyring)$'); then
        if [ -n "$files" ]; then
            pconf_files $files
        fi
    fi
fi

#############################################################
section_header "Ceph monmap"

if [ -e /etc/ceph/monmap ]; then
        monmaptool --print /etc/ceph/monmap
else
        echo "/etc/ceph/monmap did not exist"
fi

#############################################################
section_header "Ceph log files"

find_and_plog_files /var/log/ceph -type f

#############################################################
section_header "OpenStack config files"

for svc in keystone rabbitmq glance swift nova cinder neutron heat ceilometer; do
        find_and_pconf_files /etc/$svc -type f -regex '.*\.\(co?nf\(ig\)?\|ini\|json\|filters\)'

        # Keep this grouped with other rabbitmq config files
        case $svc in
            rabbitmq)
                pconf_files /etc/rabbitmq/enabled_plugins
                ;;
        esac
done

#############################################################
section_header "OpenStack log files"

for svc in keystone rabbitmq glance swift nova cinder neutron heat ceilometer; do
        find_and_plog_files /var/log/$svc -type f
done

#############################################################
section_header "Open vSwitch config files"

find_and_pconf_files /etc/openvswitch -type f

#############################################################
section_header "Open vSwitch log files"

find_and_plog_files /var/log/openvswitch -type f

#############################################################
section_header "MongoDB log files"

find_and_plog_files /var/log/mongodb -type f

#############################################################
section_header "Corosync config"

if [ -d /etc/corosync ]; then
  if files=$(find /etc/corosync/ -type f | egrep -v 'authkey$'); then
    if [ -n "$files" ]; then
      pconf_files $files
    fi
  fi
fi

#############################################################
section_header "Cluster log files"

if [ -d /var/log/cluster/ ]; then
  find_and_plog_files  /var/log/cluster   -type f
fi

#############################################################
section_header "Backup and Restore log files"
if [ -e /var/log/crowbar/backup-restore.log ]; then
  plog_files 0 /var/log/crowbar/backup-restore.log
fi

#############################################################
section_header "Barclamp configuration details collected with crowbar batch export"

if [ -e /opt/dell/bin/crowbar_batch ]; then
  crowbar batch export > /var/log/crowbar/batch-export.log
  plog_files 0 /var/log/crowbar/batch-export.log
  rm /var/log/crowbar/batch-export.log
fi
