.TH susecloud-plugin "8" "17 Jul 2012" "susecloud-plugin" "Support Utilities Manual"
.SH NAME
susecloud-plugin \- SUSE OpenStack Cloud Plugin for 
.BR supportconfig (8)
.
.SH DESCRIPTION
Supportconfig plugins add functionality to the supportconfig script. This plugin extends supportconfig's functionality to include SUSE OpenStack Cloud
information. Supportconfig saves the plugin output as plugin-susecloud.txt.

.SH FILES
.I /usr/lib/supportconfig/plugins/susecloud
.RS
The SUSE OpenStack Cloud plugin
.RE
.SH AUTHOR
Matt Barringer <mbarringer@suse.de>
.SH REPORTING BUGS
Please submit bug fixes, comments or enhancement requests via: 
.B http://bugzilla.suse.com
.SH SEE ALSO
.BR supportconfig (8)
.BR supportconfig.conf (5)
