#!/bin/bash
#############################################################
# Name:        Supportconfig Plugin for SUSE Cloud
# Description: Gathers important troubleshooting information
#              about SUSE Cloud
# License:     GPLv2
# Author:      Matt Barringer <mbarringer@suse.de>
# Modified:    2012 August 29
#############################################################

SVER=1.0.0
RCFILE="/usr/lib/supportconfig/resources/scplugin.rc"
LOG_LINES=500  # 0 means include the entire file

[ -s $RCFILE ] && . $RCFILE || { echo "ERROR: Initializing resource file: $RCFILE"; exit 1; }

validate_rpm_if_installed() {
        THISRPM=$1
        echo "#==[ Validating RPM ]=================================#"
        if rpm -q $THISRPM >/dev/null 2>&1; then
                echo "# rpm -V $THISRPM"
        
                if rpm -V $THISRPM; then
                        echo "Status: Passed"
                else
                        echo "Status: WARNING"
                fi
        else
                echo "package $THISRPM is not installed"
                echo "Status: Skipped"
        fi
        echo
}

#############################################################
section_header "Supportconfig Plugin for SUSE Cloud, v${SVER}"
# This list was generated via:
# find /mnt/suse-cloud-2.0/ -name *.rpm | sed 's/.*\///; s/-[0-9.+A-Za-z_]\+-[0-9.]\+\.\(x86_64\|noarch\)\.rpm$//' | sort
RPMLIST="
apache2-mod_fcgid
apache2-mod_wsgi
ceph
ceph-fuse
ceph-kmp-default
ceph-kmp-xen
ceph-radosgw
couchdb
createrepo
crowbar
crowbar-barclamp-ceph
crowbar-barclamp-cinder
crowbar-barclamp-crowbar
crowbar-barclamp-database
crowbar-barclamp-deployer
crowbar-barclamp-dns
crowbar-barclamp-glance
crowbar-barclamp-ipmi
crowbar-barclamp-keystone
crowbar-barclamp-logging
crowbar-barclamp-nagios
crowbar-barclamp-network
crowbar-barclamp-nova
crowbar-barclamp-nova_dashboard
crowbar-barclamp-ntp
crowbar-barclamp-openstack
crowbar-barclamp-provisioner
crowbar-barclamp-quantum
crowbar-barclamp-rabbitmq
crowbar-barclamp-swift
deltarpm
erlang
euca2ools
FastCGI
gecode
google-perftools
google-perftools-devel
libcephfs1
libedit0
librados2
librbd1
librgw1
libyaml-0-2
memcached
novnc
openstack-ceilometer
openstack-ceilometer-agent-central
openstack-ceilometer-agent-compute
openstack-ceilometer-api
openstack-ceilometer-collector
openstack-ceilometer-doc
openstack-cinder
openstack-cinder-api
openstack-cinder-backup
openstack-cinder-doc
openstack-cinder-scheduler
openstack-cinder-volume
openstack-dashboard
openstack-dashboard-branding-SLE
openstack-glance
openstack-glance-doc
openstack-heat
openstack-heat-api
openstack-heat-api-cfn
openstack-heat-api-cloudwatch
openstack-heat-doc
openstack-heat-engine
openstack-keystone
openstack-keystone-doc
openstack-nova
openstack-nova-api
openstack-nova-cells
openstack-nova-cert
openstack-nova-compute
openstack-nova-conductor
openstack-nova-console
openstack-nova-consoleauth
openstack-nova-doc
openstack-nova-novncproxy
openstack-nova-objectstore
openstack-nova-scheduler
openstack-nova-vncproxy
openstack-quantum
openstack-quantum-dhcp-agent
openstack-quantum-doc
openstack-quantum-l3-agent
openstack-quantum-lbaas-agent
openstack-quantum-linuxbridge-agent
openstack-quantum-metadata-agent
openstack-quantum-nec-agent
openstack-quantum-openvswitch-agent
openstack-quantum-ryu-agent
openstack-quantum-server
openstack-suse-macros
openstack-suse-sudo
openstack-swift
openstack-swift-account
openstack-swift-container
openstack-swift-doc
openstack-swift-object
openstack-swift-proxy
openstack-utils
openvswitch
openvswitch-kmp-default
openvswitch-kmp-trace
openvswitch-switch
perl-JSON
python-alembic
python-amqp
python-amqplib
python-anyjson
python-Beaker
python-boto
python-ceilometer
python-ceilometerclient
python-ceph
python-Cheetah
python-cinder
python-cinderclient
python-cinderclient-doc
python-cliff
python-cliff-tablib
python-cmd2
python-d2to1
python-decorator
python-deltarpm
python-distribute
python-django
python-django-appconf
python-django_compressor
python-django_openstack_auth
python-docutils
python-eventlet
python-extras
python-feedparser
python-Flask
python-flup
python-FormEncode
python-glance
python-glanceclient
python-greenlet
python-happybase
python-heat
python-heatclient
python-heatclient-doc
python-horizon
python-horizon-branding-upstream
python-hp3parclient
python-httplib2
python-importlib
python-iniparse
python-iso8601
python-Jinja2
python-jsonpatch
python-jsonpointer
python-jsonschema
python-keystone
python-keystoneclient
python-keystoneclient-doc
python-kombu
python-lockfile
python-m2crypto
python-Mako
python-MarkupSafe
python-Ming
python-msgpack-python
python-netaddr
python-nose
python-nova
python-novaclient
python-novaclient-doc
python-oslo.config
python-oslo.config-doc
python-paramiko
python-passlib
python-Paste
python-PasteDeploy
python-PasteScript
python-pecan
python-pep8
python-PrettyTable
python-psycopg2
python-py
python-pycrypto
python-Pygments
python-pymongo
python-pyOpenSSL
python-pyparsing
python-python-daemon
python-python-memcached
python-python-openid
python-pytz
python-pyudev
python-PyYAML
python-quantum
python-quantumclient
python-repoze.lru
python-requests
python-Routes
python-simplegeneric
python-simplejson
python-six
python-Sphinx
python-sphinxcontrib-httpdomain
python-sphinxcontrib-issuetracker
python-SQLAlchemy
python-sqlalchemy-migrate
python-stevedore
python-suds
python-swift
python-swiftclient
python-swiftclient-doc
python-tablib
python-Tempita
python-thrift
python-versiontools
python-warlock
python-WebOb
python-websockify
python-WebTest
python-Werkzeug
python-wsgiref
python-WSME
python-xattr
rabbitmq-server
rabbitmq-server-plugins
release-notes-suse-cloud
ruby-devel
rubygem-actionmailer-2_3
rubygem-actionpack-2_3
rubygem-activerecord-2_3
rubygem-activeresource-2_3
rubygem-activesupport-2_3
rubygem-addressable
rubygem-amqp
rubygem-bundler
rubygem-bunny
rubygem-chef
rubygem-chef-doc
rubygem-chef-expander
rubygem-chef-expander-doc
rubygem-chef-server
rubygem-chef-server-api
rubygem-chef-server-api-doc
rubygem-chef-server-doc
rubygem-chef-solr
rubygem-chef-solr-doc
rubygem-coderay
rubygem-cookiejar
rubygem-cstruct
rubygem-daemons
rubygem-dep_selector
rubygem-em-http-request
rubygem-em-socksify
rubygem-erubis-2_7
rubygem-eventmachine
rubygem-extlib
rubygem-fast_xs
rubygem-haml
rubygem-highline
rubygem-http_parser.rb
rubygem-i18n
rubygem-json
rubygem-kgio
rubygem-kwalify
rubygem-libxml-ruby
rubygem-merb-assets
rubygem-merb-core
rubygem-merb-haml
rubygem-merb-helpers
rubygem-merb-param-protection
rubygem-mime-types
rubygem-mixlib-authentication
rubygem-mixlib-cli
rubygem-mixlib-config
rubygem-mixlib-log
rubygem-mixlib-shellout
rubygem-moneta
rubygem-net-http-digest_auth
rubygem-net-ssh
rubygem-net-ssh-gateway
rubygem-net-ssh-multi
rubygem-ohai
rubygem-pg
rubygem-polyglot
rubygem-rack
rubygem-rails-2_3
rubygem-rainbows
rubygem-raindrops
rubygem-rake
rubygem-rest-client
rubygem-ruby-shadow
rubygems
rubygem-sass
rubygem-simple-navigation
rubygem-syslogger
rubygem-systemu
rubygem-thin
rubygem-treetop
rubygem-unicorn
rubygem-uuidtools
rubygem-wsman
rubygem-xml-simple
rubygem-yajl-ruby
sleshammer
supportutils-plugin-susecloud
susecloud-admin_en-pdf
susecloud-deployment_en-pdf
susecloud-manuals_en
suse-cloud-release
suse-cloud-release-cd
susecloud-user_en-pdf
yast2-crowbar
yum-common
yum-metadata-parser
"

for THISRPM in $RPMLIST; do
        validate_rpm_if_installed $THISRPM
done

find_and_pconf_files () {
        [ -d "$1" ] || return 0
        FILES=$(find "$@" ! -name \*.gz ! -name \*.bz2)
        if [ -n "$FILES" ]; then
                pconf_files $FILES
        fi
}

find_and_plog_files () {
        [ -d "$1" ] || return 0
        FILES=$(find "$@" ! -name \*.gz ! -name \*.bz2)
        if [ -n "$FILES" ]; then
                plog_files $LOG_LINES $FILES
        fi
}

#############################################################
section_header "Crowbar"

pconf_files \
	/etc/crowbar.install.key \
	/tmp/bc-template-dns.json \
	/opt/dell/chef/data_bags/crowbar/bc-template-*.json \
	/var/chef/cache/chef-stacktrace.out
find_and_pconf_files /etc/crowbar                         -type f
find_and_plog_files  /opt/dell/crowbar_framework/log      -type f
find_and_plog_files  /var/log/nodes                       -type f
find_and_plog_files  /var/log/barclamps                   -type f
find_and_plog_files  /var/log -path /var/log/crowbar\*    -type f
find_and_plog_files  /var/log/apache2                     -type f
find_and_plog_files  /var/log/crowbar                     -type f
plugin_tag "admin node PXE / TFTP configuration"
find                 /srv/tftpboot/discovery/pxelinux.cfg -ls
echo; echo
find_and_pconf_files /srv/tftpboot/discovery/pxelinux.cfg -type f

#############################################################
section_header "Chef"

# Don't capture private keys/certificates, just show the inode info
[ -d /etc/chef ] && find /etc/chef -type f -name \*.pem -ls
echo; echo
find_and_pconf_files /etc/chef       -type f  ! -name \*.pem

find_and_plog_files  /var/log/chef   -type f
find_and_plog_files  /root           -name screenlog.\*

#############################################################
section_header "Ceph config"

[ -d /etc/ceph ] && FILES=$(find /etc/ceph -type f | egrep -v '(/monmap|\.keyring)$') || FILES=""
if [ -n "$FILES" ]; then
        pconf_files $FILES
fi

#############################################################
section_header "Ceph monmap"

if [ -e /etc/ceph/monmap ]; then
        monmaptool --print /etc/ceph/monmap
else
        echo "/etc/ceph/monmap did not exist"
fi

#############################################################
section_header "Ceph log files"

find_and_plog_files /var/log/ceph -type f

#############################################################
section_header "OpenStack"

for svc in keystone rabbitmq glance swift nova; do
        find_and_plog_files /var/log/$svc -type f
done
